theme: minima
title: Pete Stopoulos's Page
author: Pete Stopoulos  
email: PeteStopoulos@gmail.com
description: Page created for MSSA

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  PeteStopoulos!

show_excerpts: true # set to false to remove excerpts on the homepage
